// src/services/aiImageService.js
/**
 * Build the prompt for the AI image generator.
 * @param {string} name - Recipe name (e.g., "Spicy Thai Coconut Curry")
 * @param {string[]} ingredients - Array of key ingredients (5‑8 items)
 * @param {string} theme - Visual theme chosen by the user
 * @returns {string} Prompt string ready to be sent to the AI model
 */
export function buildImagePrompt(name, ingredients, theme) {
    const ingredientList = ingredients.join(', ');
    return `Generate a photorealistic, appealing image of ${name}. The image must visually feature and suggest the presence of the key components from the following list: ${ingredientList}. The overall presentation must strictly adhere to the ${theme} style. The image should be rendered in professional food photography, studio lighting with a depth of field, suitable for use as a recipe book cover. Output a high resolution square (1024×1024) JPEG.`;
}

/**
 * Call the Vercel serverless endpoint that talks to OpenAI.
 * @param {string} prompt - Prompt generated by buildImagePrompt
 * @returns {Promise<string>} URL of the generated image
 */
export async function generateCoverImage(prompt) {
    const resp = await fetch('/api/generateImage', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt }),
    });

    if (!resp.ok) {
        const err = await resp.text();
        throw new Error(`Image generation failed: ${err}`);
    }

    const { imageUrl } = await resp.json();
    return imageUrl;
}
